### ISSUE TITLE
WARNING:modules.face_restoration_utils:Unable to load face-restoration model                                                                                

### ISSUE THREAD

**Issue by axemaster** [light-and-ray/sd-webui-hardware-info-in-metadata#4] opened 2024-07-06 09:43 UTC
This is odd, as I am not using GFPGAN.

```
WARNING:modules.face_restoration_utils:Unable to load face-restoration model                                                                                | 30/600 [00:42<14:01,  1.48s/it]Traceback (most recent call last):
  File "/Users/timshea/work/A1111/SDWU/stable-diffusion-webui/modules/face_restoration_utils.py", line 150, in restore_with_helper
    self.net = self.load_net()
  File "/Users/timshea/work/A1111/SDWU/stable-diffusion-webui/modules/gfpgan_model.py", line 46, in load_net
    raise ValueError("No GFPGAN model found")
ValueError: No GFPGAN model found
*** Error running postprocess_image: /Users/timshea/work/A1111/SDWU/stable-diffusion-webui/extensions/sd-webui-hardware-info-in-metadata/scripts/hardware_info_in_metadata.py
    Traceback (most recent call last):
      File "/Users/timshea/work/A1111/SDWU/stable-diffusion-webui/modules/scripts.py", line 897, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/Users/timshea/work/A1111/SDWU/stable-diffusion-webui/modules/scripts_auto_postprocessing.py", line 24, in postprocess_image
        self.script.process(pp, **args_dict)
      File "/Users/timshea/work/A1111/SDWU/stable-diffusion-webui/extensions/sd-webui-hardware-info-in-metadata/scripts/hardware_info_in_metadata.py", line 125, in process
        pp.info["Time taken"] = self.getElapsedTime()
      File "/Users/timshea/work/A1111/SDWU/stable-diffusion-webui/extensions/sd-webui-hardware-info-in-metadata/scripts/hardware_info_in_metadata.py", line 115, in getElapsedTime
        elapsed = time.perf_counter() - self.start
    TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

**Comment by light-and-ray** [comment] 2024-07-06 10:55
Thanks for reporting. I will discover why self.start timer cannot be initilized

**Comment by light-and-ray** [comment] 2024-07-06 10:55
The message is really strange

**Comment by light-and-ray** [comment] 2024-07-06 10:56
Which version of webui you use?

**Comment by axemaster** [comment] 2024-07-08 08:30
> Which version of webui you use?

on commit 1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0
If I pull latest it stops working on my hardware.

**Comment by axemaster** [comment] 2024-07-08 08:39
pulled extension. message  has changed from warning to error.

```
*** Error running postprocess_image: /Users/timshea/work/A1111/SDWU/stable-diffusion-webui/extensions/sd-webui-hardware-info-in-metadata/scripts/hardware_info_in_metadata.py
    Traceback (most recent call last):
      File "/Users/timshea/work/A1111/SDWU/stable-diffusion-webui/modules/scripts.py", line 897, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/Users/timshea/work/A1111/SDWU/stable-diffusion-webui/modules/scripts_auto_postprocessing.py", line 24, in postprocess_image
        self.script.process(pp, **args_dict)
      File "/Users/timshea/work/A1111/SDWU/stable-diffusion-webui/extensions/sd-webui-hardware-info-in-metadata/scripts/hardware_info_in_metadata.py", line 125, in process
        if self.start is not None:
      File "/Users/timshea/work/A1111/SDWU/stable-diffusion-webui/extensions/sd-webui-hardware-info-in-metadata/scripts/hardware_info_in_metadata.py", line 115, in getElapsedTime
        elapsed = time.perf_counter() - self.start
    TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

I get this error for every image generated in a batch.

**Comment by light-and-ray** [comment] 2024-07-08 08:58
Version is okay. Btw you can try to remove venv dir if you want to use newer version. Very soon 1.10 will be released

I can't reproduce your bug. What you do. Extras->batch of something else?

**Comment by axemaster** [comment] 2024-07-09 06:59
> Version is okay. Btw you can try to remove venv dir if you want to use newer version. Very soon 1.10 will be released
> 
> I can't reproduce your bug. What you do. Extras->batch of something else?

it's just txt2image with dynamic prompts, and GFGPAN is disabled.

**Comment by light-and-ray** [comment] 2024-07-09 09:12
Thanks for explaining the problem. I'm assuming I used a wrong callback for initialization. Strange that I didn't have this problem. Can you pull and check it now?

**Closed as completed** 2024-07-11 16:30 UTC
